apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    spec:
      containers:
      - name: server
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/gcp/sa-key.json
        volumeMounts:
        - name: service-account
          mountPath: /var/gcp
          readOnly: true
      volumes:
      - name: service-account
        secret:
          secretName: gcp-service-account
