apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../kubernetes-manifests
patchesStrategicMerge:
- adservice.yaml
- checkoutservice.yaml
- currencyservice.yaml
- emailservice.yaml
- frontend.yaml
- loadgenerator.yaml
- paymentservice.yaml
- productcatalogservice.yaml
- recommendationservice.yaml
- shippingservice.yaml
