apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    spec:
      containers:
      - name: main
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/gcp/sa-key.json
        volumeMounts:
        - name: service-account
          mountPath: /var/gcp
          readOnly: true
      volumes:
      - name: service-account
        secret:
          secretName: gcp-service-account
